name: CI/CD

on:
  push:
    branches:
      - main

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mire

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          lein: 'latest'

      - name: Run tests
        run: lein test

  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mire #razv

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          lein: 'latest'

      - name: Build uberjar
        run: lein uberjar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t ghcr.io/layar247/gfnrlp:latest .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/layar247/gfnrlp:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Check SSH port accessibility
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat-traditional
          nc -zv 212.192.134.135 58529

      - name: SSH deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 212.192.134.135
          username: matsumoto
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 58529
          debug: true
          script: |
            podman login ghcr.io -u ${{ github.actor }} --password ${{ secrets.GHCR_PAT }}
            podman pull ghcr.io/layar247/gfnrlp:latest
            podman stop gfnrlp || true
            podman rm gfnrlp || true
            podman run -d --name gFnRLP -p 3333:3333 ghcr.io/layar247/gfnrlp:latest

      - name: Verify container is running
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 212.192.134.135
          username: matsumoto
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 58529
          debug: true
          script: |
            podman ps --filter "name=gFnRLP"
